<template>
<div class="bg-maintheme min-h-screen text-gray-300">
  <div class="flex flex-col items-center justify-center px-4 pt-16 mx-auto sm:max-w-xl md:max-w-full lg:pt-24 md:px-0 ">
    <div class="flex flex-col items-center max-w-2xl md:px-8">
      <div class="max-w-xl mb-10 md:mx-auto sm:text-center lg:max-w-2xl md:mb-12">
        <Title />
        <p class="text-base md:text-lg">
          Thanks for testing my app! <a href="www.feedback.com" class="underline">Feedback me.</a>
        </p>
      </div>
        
    </div>


    
    <div class="w-4/5 md:w-3/6 mx-auto items-center justify-center">
        <div class="flex flex-col items-center gap-2">
            
            <span class="flex">
                <button @click="doCopy" class="inline-flex items-center h-10 px-5 text-indigo-100 transition-colors duration-150 bg-blue-500 rounded-lg focus:shadow-outline hover:bg-blue-800">
                <span class="mr-2">{{copyState}}</span>
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 cursor-pointer" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                </svg>
</button>
        </span>

            <textarea v-model="message" @click="doCopy" id="description" class=" overflow-hidden shadow-blue border border-solid border-blue-500 cursor-pointer
            w-full 
            h-80 
            text-gray-400 
            outline-none 
            rounded-md 
            bg-maintheme 
            form-control
            block
            px-3
            py-1.5
            text-base
            font-normal
            bg-clip-padding
            rounded
            transition
            ease-in-out whitespace-pre hover:bg-gray-800
            m-0">##############################################################
##                                                                                                                                                      ##
##        GENERATED BY CSGO CONFIG MANAGER V1.0.0                                                               ##
##                                                                                                                                                      ##
##############################################################

clear

// #### RATES ####
rate "1"
cl_cmdrate "128"
cl_updaterate "128"


// #### INTERP ####
cl_interp "0"
cl_interp_ratio "1"
cl_interpolate "1"
cl_lagcompensation "1"


// #### MOUSE ####
m_customaccel "0"
m_customaccel_exponent "1.05"
m_customaccel_max "0"
m_customaccel_scale "0.04"
m_forward "1"
m_mouseaccel1 "0"
m_mouseaccel2 "0"
m_mousespeed "0"
m_pitch "0.022"
m_rawinput "1"
m_side "0.8"
m_yaw "0.022"
sensitivity "2.7"
ui_steam_overlay_notification_position "topright"
mm_dedicated_search_maxping "69"


// #### VIEWMODEL ####
viewmodel_presetpos "4"
viewmodel_fov "1"
viewmodel_offset_x "2.9"
viewmodel_offset_y "2"
viewmodel_offset_z "-1.5"


// #### BOB ####
cl_bob_lower_amt "0"
cl_bobamt_lat "0"
cl_bobamt_vert "0"
cl_bobcycle "1"
cl_bob "0.01"
cl_bobcycle "0.8"
cl_bobup "0.5"


// #### CROSSHAIR ####
alias ch_color1 "cl_crosshair_outlinethickness 1; cl_crosshairalpha "201"; cl_crosshaircolor 2; cl_crosshaircolor_b 50; cl_crosshaircolor_g 0; cl_crosshaircolor_r "255"; cl_crosshairdot 0; cl_crosshairgap -2; cl_crosshairgap_useweaponvalue 0; cl_crosshairscale 0; cl_crosshairsize 3; cl_crosshairstyle 4; cl_crosshairthickness 1; cl_crosshairusealpha 1; cl_fixedcrosshairgap -1; alias ch_color ch_color2"
alias ch_color2 "cl_crosshair_outlinethickness 0.500000; cl_crosshairalpha "250"; cl_crosshaircolor 5; cl_crosshaircolor_b 255; cl_crosshaircolor_g 0; cl_crosshaircolor_r "64"; cl_crosshairdot 0; cl_crosshairgap -4.500000; cl_crosshairgap_useweaponvalue 0; cl_crosshairscale 1700; cl_crosshairsize 2.500000; cl_crosshairstyle 4; cl_crosshairthickness 0.500000; cl_crosshairusealpha 1; cl_fixedcrosshairgap -10; alias ch_color ch_color3"
alias ch_color3 "cl_crosshair_outlinethickness 1; cl_crosshairalpha "250"; cl_crosshaircolor 5; cl_crosshaircolor_b 144; cl_crosshaircolor_g 195; cl_crosshaircolor_r "27"; cl_crosshairdot 1; cl_crosshairgap -1; cl_crosshairgap_useweaponvalue 0; cl_crosshairscale 0; cl_crosshairsize 1; cl_crosshairstyle 5; cl_crosshairthickness 0.4; cl_crosshairusealpha 1; cl_fixedcrosshairgap 3; alias ch_color ch_color4"
alias ch_color4 "cl_crosshair_outlinethickness 1; cl_crosshairalpha "201"; cl_crosshaircolor 2; cl_crosshaircolor_b 50; cl_crosshaircolor_g 0; cl_crosshaircolor_r "255"; cl_crosshairdot 0; cl_crosshairgap -2; cl_crosshairgap_useweaponvalue 0; cl_crosshairscale 0; cl_crosshairsize 1; cl_crosshairstyle 4; cl_crosshairthickness 1; cl_crosshairusealpha 1; cl_fixedcrosshairgap -1; alias ch_color ch_color5"
alias ch_color5 "cl_crosshair_drawoutline "1"; cl_crosshair_outlinethickness "0.1"; cl_crosshairalpha "999"; cl_crosshairgap "-3"; cl_crosshairscale "0"; cl_crosshairsize "1"; cl_crosshairstyle "4"; cl_crosshairthickness "0"; alias ch_color ch_color1"
cl_crosshair_sniper_width "2"


// #### CL_ ####
cl_forcepreload "0"
cl_predict "1"
cl_predictweapons "1"
cl_mouseenable "1"
cl_forcepreload "0"
cl_downloadfilter "all"
cl_disablehtmlmotd "1"
cl_disablefreezecam "1"
cl_teammate_colors_show "1"
cl_autowepswitch "0"
cl_use_opens_buy_menu "0"
cl_join_advertise "2"
cl_color "0"
cl_viewmodel_shift_left_amt "0"
cl_viewmodel_shift_right_amt "0"
cl_autohelp "0"
cl_showhelp "0"
cl_righthand "1"
cl_showloadout "1"
cl_loadout_colorweaponnames "1"
cl_show_clan_in_death_notice "1"
cl_teamid_overhead_always 1
cl_teamid_overhead "1" 
cl_teamid_overhead_maxdist "3000" 
cl_teamid_overhead_name_alpha "255"
cl_teamid_overhead_name_fadetime "0"
+cl_show_team_equipment


// #### HUD & RADAR ####
hud_takesshots "0"
hud_showtargetid "0"
hud_scaling "0.75"
hud_scaling "0.75"
cl_hud_radar_scale "1.2"
cl_hud_playercount_pos "0"
cl_hud_playercount_showcount "0"
cl_hud_color "8"
cl_hud_background_alpha "0.5"
cl_hud_bomb_under_radar "1"
cl_hud_healthammo_style "0"
cl_radar_always_centered "1"
cl_radar_icon_scale_min "0.4"
cl_radar_rotate "1"
cl_radar_scale "0.45"


// #### FPS ####
fps_max "0"
fps_max_menu "144"


// #### VOLUME ####
snd_menumusic_volume "0"
voice_enable "1"
voice_scale "0.3"
voice_mixer_volume "1"
lobby_voice_chat_enabled "0"
snd_deathcamera_volume "0.0"
snd_mapobjective_volume "0.0"
snd_menumusic_volume "0"
snd_musicvolume "0.00"
snd_roundend_volume "0.0"
snd_roundstart_volume "0.00"
snd_tensecondwarning_volume "0.00"


// #### SOUND OPTIMIZATIONS ####
snd_surround_speaker_pan_exponent "1.5"
snd_surround_speaker_pan_radial_weight "0"
snd_rear_surround_speaker_position "135"
snd_front_surround_speaker_position "45"
snd_rear_speaker_scale "0.9"
snd_use_hrtf "0"
dsp_enhance_stereo "0"
snd_mixahead "0.025"
snd_pitchquality "1"


// #### NET ####
net_steamcnx_allowrelay "1"
net_graph "1"
net_graphheight "0"
net_graphproportionalfont "0.5"
net_graphpos "2"


// #### SV_ ####
sv_forcepreload "1"


// #### BINDS ####
bind "KP_MINUS" "voice_inputfromfile 1; voice_loopback 1; +voicerecord"
bind "KP_PLUS" "voice_inputfromfile 0; voice_loopback 0; -voicerecord"
unbind "w"
unbind "s"
unbind "a"
unbind "d"
bind "leftarrow" "buy hegrenade;"
bind "downarrow" "buy flashbang;"
bind "rightarrow" "buy smokegrenade;"
bind "uparrow" "buy molotov; buy incgrenade;"
bind "h" "say ﷽﷽ ﷽﷽﷽ ﷽﷽﷽ ﷽﷽﷽ ﷽﷽﷽ ﷽﷽﷽ ﷽﷽﷽ ﷽﷽﷽ ﷽﷽﷽﷽ ﷽﷽﷽ ﷽﷽﷽ ﷽﷽﷽ ﷽﷽�"
bind "x" "radio2; jeringue"
bind "MWHEELDOWN" "+jump"
bind "SPACE" "+jump"
bind "MWHEELUP" "+duck"
bind alt "sv_cheats 1; noclip"
bind "w" "+forward"; 
bind "s" "+back"; 
bind "a" "+moveleft"; 
bind "d" "+moveright";
bind mouse3 "ch_color"
bind "F3" "autobuy"
unbind "F4"
unbind "F5"
unbind "F6"
unbind "F7"
unbind "F10"
alias +netg "net_graph 1;+showscores";alias -netg "net_graph 0;-showscores";bind TAB "+netg";
bind "space" "+jumpthrow"


// #### ALIAS ####
alias ch_color ch_color1
alias "+jumpthrow" "+jump;-attack"
alias "-jumpthrow" "-jump"


// #### VARIETY ####
closeonbuy "1"


// #### UNKNOWN/UNCATEGORIZED ####


clear











windows_speaker_config "6"






player_nevershow_communityservermessage "1"
gameinstructor_enable "0"




































safezonex "1"
safezoney "1"

developer "0"







mat_queue_mode "1"






host_writeconfig
clear
echo "
echo "
echo "
echo "
echo "
echo "
echo "
echo "
echo "

host_writeconfig
clear
echo "##############################################################"
echo "##                                                          ##"
echo "##        GENERATED BY CSGO CONFIG OPTIMIZER V1.0.0         ##"
echo "##                                                          ##"
echo "##############################################################"







            </textarea>

        </div>
    </div>
  </div>
</div>
</template>

<script>
    export default {
        data() {
            return {
                message: 'Copy These Text',
                copyState: 'COPY CONFIG',
            }
        },
        methods: {
            showCopied() {
                this.copyState = 'COPIED!' 
                setTimeout(() => {
                    this.copyState = 'COPY CONFIG' 
                }, 3500);
            
            },
            doCopy: function () {
                this.$copyText(this.message).then(function (e) {
                console.log(e.text)
                }, function (e) {
                alert('An error happened!')
                console.log(e)
                }).then(
                    this.showCopied()
                )
            },
        }
    }
</script>

<style scoped>
.title-gradient {
  background: linear-gradient(to right, hsl(83, 100%, 56%), hsl(216, 100%, 55%));
  background-clip: text;
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}
</style>
